# Generated by Django 4.2.30 on 2026-04-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MICDA_BLOG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
