# Generated by Django 4.2.30 on 2026-04-10 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MICDA_BLOG', '0002_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contenue',
            new_name='contenu',
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='MICDA_BLOG.article')),
            ],
        ),
    ]
