# Generated by Django 4.2.30 on 2026-04-10 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MICDA_BLOG', '0003_rename_contenue_article_contenu_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='nom',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
