# Generated by Django 4.2.30 on 2026-04-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MICDA_BLOG', '0005_alter_commentaire_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MICDA_BLOG.article'),
        ),
    ]
