# Generated by Django 4.2.30 on 2026-04-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MICDA_BLOG', '0008_article_auteur_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='Profiles/'),
        ),
    ]
